[package]
name = "simple_cli_calculator"
version = "0.1.0"
authors = ["Saad Ahmed <saad@seedcode.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
